APP_TITLE = "Spek Avcısı V22 Portfolio Pro"
CACHE_TTL_SINGLE = 600
CACHE_TTL_SCAN = 900
DEFAULT_MARKET_SCORE = 55

DEFAULT_PORTFOLIO = ["THYAO", "ASELS", "TUPRS"]
DEFAULT_FAVORITES = ["KCHOL", "ISCTR", "EREGL"]
