BIST_SYMBOLS = sorted(set("""
A1CAP ACSEL ADEL ADESE ADGYO AEFES AFYON AGESA AGHOL AGROT AHGAZ AKBNK
AKCNS AKENR AKFGY AKFYE AKGRT AKMGY AKSA AKSEN AKSGY AKSUE AKYHO ALARK
ALBRK ALCAR ALCTL ALFAS ALGYO ALKA ALKIM ALMAD ALTNY ANSGR ARCLK ARDYZ
ARENA ARSAN ASELS ASTOR ASUZU ATAGY ATAKP ATATP AVGYO AVHOL AVOD AVPGY
AYCES AYDEM AYEN AYGAZ BAGFS BAKAB BALAT BASCM BAYRK BEGYO BERA BESLR
BFREN BIENY BIGCH BIMAS BINHO BIOEN BIZIM BJKAS BLCYT BMSCH BMSTL BNTAS
BOSSA BRISA BRKSN BRLSM BRMEN BRSAN BRYAT BSOKE BTCIM BUCIM BURCE BVSAN
CANTE CCOLA CELHA CEMAS CEMTS CEOEM CIMSA CLEBI CMBTN CMENT CONSE CRFSA
CVKMD CWENE DAGHL DAGI DAPGM DARDL DESA DESPC DEVA DGATE DGNMO DOAS DOHOL
DYOBY EBEBK ECILC ECZYT EDATA EDIP EGEEN EGSER EKGYO EKOS EKSUN ELITE
EMKEL ENERY ENJSA ENKAI EREGL ESCOM ESEN EUPWR EUREN FENER FONET FORTE
FROTO GARAN GEDIK GESAN GLYHO GOKNR GOODY GOZDE GRSEL GSDHO GSRAY GUBRF
GWIND HALKB HATSN HEDEF HEKTS HKTM HLGYO HOROZ HRKET HTTBT HUBVC ICBCT
IDGYO IEYHO IHAAS IHLAS IHLGM IMASM INDES INFO INVEO INVES IPEKE ISCTR
ISDMR ISFIN ISGYO ISMEN ISSEN IZENR IZMDC JANTS KAREL KARSN KATMR KAYSE
KBORU KCAER KCHOL KERVT KFEIN KIMMR KLGYO KLKIM KLSER KMPUR KONTR KONYA
KORDS KOTON KOZAA KOZAL KRDMD KRONT KRVGD KUTPO KUYAS LIDER LILAK LKMNH
LOGO MAVI MEDTR MEGMT MERIT METRO MGROS MIATK MOBTL MPARK MTRKS NATEN
NETAS NTHOL NUHCM ODAS ODINE OFSYM ONCSM ORCAY ORGE OTKAR OYAKC OZGYO
OZKGY PASEU PATEK PCILT PEGYO PEKGY PENTA PETKM PGSUS PINSU PNLSN PNSUT
POLHO PRKME PSGYO RALYH RAYSG REEDR RGYAS RODRG RTALB RUBNS RYGYO RYSAS
SAHOL SASA SAYAS SDTTR SEKUR SELEC SELVA SISE SKBNK SKTAS SMART SMRTG
SNGYO SOKE SOKM SRVGY SUWEN TABGD TATGD TAVHL TCELL TEKTU THYAO TKFEN
TKNSA TMSN TOASO TRCAS TRGYO TRILC TSKB TSPOR TTKOM TTRAK TUKAS TUPRS
TUREX TURSG UFUK ULKER ULUUN VAKBN VAKFN VBTYZ VERUS VESBE VESTL YATAS
YEOTK YIGIT YKBNK YKSLN YUNSA ZOREN
""".split()))
